name: encrypt_db_example
description: Demonstrates how to use the encrypt_db plugin.
version: 0.0.1+1
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=2.18.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  encrypt_db:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
