name: encrypt_db
description: LocalStorage for Flutter with encryption like SharedPreferences
version: 0.0.8
homepage: https://opensource.appworld.in
repository: https://github.com/debojyoti452/encrypt_local_storage.git
issue_tracker: https://github.com/debojyoti452/encrypt_local_storage/issues
documentation: https://github.com/debojyoti452/encrypt_local_storage/blob/main/README.md


environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.3
  dart_std: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.swing.encrypt_db
        pluginClass: EncryptDbPlugin
      ios:
        pluginClass: EncryptDbPlugin
