name: encrypt_db
description: A Swing Technologies Product.
version: 0.0.1
homepage: https://opensource.appworld.in

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.3
  dart_std: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.swing.encrypt_db
        pluginClass: EncryptDbPlugin
#      ios:
#        pluginClass: EncryptDbPlugin
